#!/usr/bin/env python3
"""Tranche B: Aug 1796 – Aug 1799 French + own translations."""
import json, sys
sys.path.insert(0, "sources")
from common import push

NAP = {"author": "Napoleon Bonaparte", "handle": "@bonaparte", "accountType": "person"}
ARCH = "Correspondance de Napoléon Ier, Second Empire ed. (Paris, 1858), Vols. II–V — public domain (French)"
TR = " Translated for Chronicle from the public-domain French; original below."
def U(v): return f"https://archive.org/details/correspondancede{v:02d}napouoft"

# (iso, vol, loc, toline, eid, ctx, fr, en)
REC = [
 ("1796-08-02", 2, "Italy", "Army composition order", "italy-1796",
  "New line-up: 4th, 45th, 5th; 69th's battalions; light 17th.",
  "4e, 45e et 5e demi-brigade de ligne; 1er et 2e bataillon de la 69e et la 17e demi-brigade d'infanterie légère.",
  "4th, 45th and 5th line; 1st and 2nd of the 69th; light 17th."),
 ("1796-08-02", 2, "Montechiaro", "To Kilmaine", "italy-1796",
  "Kilmaine holds Montechiaro with all cavalry, watching right.",
  "Il est ordonné au général Kilmaine de rester à Montechiaro avec toute sa cavalerie.",
  "Kilmaine stays at Montechiaro with all his cavalry."),
 ("1796-08-03", 2, "Italy", "To Faultrier (Lonato)", "italy-1796",
  "You saw today's battles: 5,000 prisoners, many killed.",
  "Vous devez avoir été témoin des batailles données à l'ennemi aujourd'hui: nous lui avons pris 5,000 hommes, tué un grand nombre.",
  "You witnessed today's battles: 5,000 prisoners taken, many killed."),
 ("1796-08-03", 2, "Italy", "To Kilmaine (grenadiers)", "italy-1796",
  "100 grenadiers and 50 horse detailed.",
  "Le général Kilmaine donnera des ordres pour que 100 grenadiers et un détachement de 50 chevaux marchent.",
  "Kilmaine details 100 grenadiers and 50 horse to march."),
 ("1796-08-04", 2, "Bozzolo", "To Gaultier", "italy-1796",
  "Bozzolo to Castenedolo at once with all headquarters kit.",
  "Il est ordonné au général Gaultier de partir sur-le-champ de Bozzolo pour se rendre à Castenedolo.",
  "Gaultier marches Bozzolo to Castenedolo at once."),
 ("1796-08-04", 2, "Italy", "To Joubert", "italy-1796",
  "Castiglione delle Stiviere by six o'clock.",
  "Il est ordonné au général Joubert de partir pour se rendre à Castiglione delle Stiviere, où il devra être arrivé à six heures.",
  "Joubert at Castiglione delle Stiviere by six o'clock."),
 ("1796-09-03", 2, "Trento", "To Vaubois", "italy-1796",
  "4:30 p.m.: Masséna at Ala; tomorrow 8 or 9 she moves.",
  "Le général Vaubois est prévenu que la division du général Masséna est arrivée à Ala; que demain, à huit ou neuf heures du matin, elle se mettra en marche.",
  "Vaubois note: Masséna reached Ala; tomorrow 8 or 9 a.m. she marches."),
 ("1796-09-06", 2, "Italy", "To the Directory (Naples)", "italy-1796",
  "If Naples is wanted, send reinforcements seriously.",
  "Si vous voulez, Citoyens Directeurs, que l'on aille à Naples, songez sérieusement à m'envoyer des renforts.",
  "If Naples is wanted, Citizen Directors, seriously consider reinforcements."),
 ("1796-09-06", 2, "Trento", "To Masséna", "italy-1796",
  "Whole division, artillery, 100 dragoons: leave at once.",
  "Il est ordonné au général Masséna de partir avec toute sa division, son artillerie et les 100 hommes du 15e dragons.",
  "Masséna marches with all, artillery and 100 dragoons."),
 ("1796-09-06", 2, "Milan", "To Baraguey (cavalry)", "italy-1796",
  "All Milan disposable cavalry to Peschiera at once.",
  "Le général commandant à Milan fera partir au plus tôt pour Peschiera tout ce qui se trouve à Milan de disponible en cavalerie.",
  "Milan sends all disposable cavalry to Peschiera at once."),
 ("1796-09-07", 2, "Italy", "To Masséna (2 a.m.)", "italy-1796",
  "Masséna marches at 2 a.m. in greatest order.",
  "Le général en chef ordonne au général Masséna de partir, demain 22, à deux heures du matin, dans le plus grand ordre.",
  "Masséna marches tomorrow 22nd at 2 a.m. in greatest order."),
 ("1796-09-09", 2, "Italy", "To Augereau (9:30 p.m.)", "italy-1796",
  "9:30 p.m.: arrived here with all forces, posts chased.",
  "Le général en chef me charge de vous prévenir que nous sommes arrivés ici, avec toutes nos forces, après en avoir chassé quelques postes.",
  "Arrived here with all forces, chasing enemy posts."),
 ("1796-10-02", 2, "Italy", "To the Directory (Lombardy)", "italy-1796",
  "Lombardy pronounces daily; one great class waits to throw the glove.",
  "Le peuple de la Lombardie se prononce chaque jour davantage.",
  "Lombardy's people pronounce daily for us."),
 ("1796-10-02", 2, "Italy", "To the Emperor", "italy-1796",
  "Majesty, Europe desires peace; this disastrous war lasted too long.",
  "Majesté, l'Europe veut la paix. Cette guerre désastreuse dure depuis trop longtemps.",
  "Majesty, Europe desires peace; this disastrous war lasted too long."),
 ("1796-10-03", 2, "Milan", "To Berthier (pillagers)", "italy-1796",
  "Patrols Verona–Bassano against French pillagers.",
  "Vous donnerez ordre qu'il soit fait des patrouilles sur la route de Vérone à Bassano, pour arrêter les excès des militaires français.",
  "Patrol Verona–Bassano against French soldiers' excesses."),
 ("1796-10-03", 2, "Milan", "To Denniee (wounded)", "italy-1796",
  "Unserviceable wounded to Lyon under war minister's orders.",
  "Je vous prie d'ordonner que tous les blessés hors d'état de servir soient transférés à Lyon.",
  "Transfer all unserviceable wounded to Lyon."),
 ("1796-10-04", 2, "Milan", "Modena contribution", "italy-1796",
  "Modena's unpaid contribution had last term the 4th Messidor.",
  "Les conditions de l'armistice conclu avec le duc de Modène n'ont pas été remplies.",
  "Modena's armistice conditions stand unfulfilled."),
 ("1796-10-02", 2, "Italy", "To the Directory (Lombardy)", "italy-1796",
  "Lombardy pronounces daily.",
  "Le peuple de la Lombardie se prononce chaque jour davantage.",
  "Lombardy's people pronounce daily for us."),
 ("1796-10-02", 2, "Italy", "To the Emperor", "italy-1796",
  "Majesty, Europe desires peace; this disastrous war lasted too long.",
  "Majesté, l'Europe veut la paix. Cette guerre désastreuse dure depuis trop longtemps.",
  "Majesty, Europe desires peace; this disastrous war lasted too long."),
 ("1796-10-04", 2, "Milan", "Modena contribution", "italy-1796",
  "Modena's unpaid contribution had last term the 4th Messidor.",
  "Les conditions de l'armistice conclu avec le duc de Modène n'ont pas été remplies.",
  "Modena's armistice conditions stand unfulfilled."),
 ("1796-11-03", 2, "Italy", "To Sucy (sans-culottes)", "italy-1796",
  "Southern sans-culottes: purge the Republic of tyrants.",
  "Les sans-culottes du Midi ne doivent avoir d'autre sollicitude que de purger le territoire de la République des tyrans.",
  "Southern sans-culottes: purge the Republic of tyrants."),
 ("1796-11-02", 2, "Verona", "Citadel supplied", "italy-1796",
  "Verona citadel victualled 20 days for 600, plus Saint-Pierre.",
  "Faire approvisionner sur-le-champ la citadelle de Vérone, pour 20 jours et pour 600 hommes.",
  "Victual Verona citadel at once, 20 days for 600 men."),
 ("1796-11-02", 2, "Verona", "To Masséna (enemy passed)", "italy-1796",
  "Masséna reports the enemy passed: armies take note.",
  "Le général en chef vient de recevoir la lettre par laquelle vous annoncez que l'ennemi a passé.",
  "Your letter announcing the enemy's passage received."),
 ("1796-11-02", 2, "Verona", "Lombard legion order", "italy-1796",
  "Lombard legion's 1st cohort to Verona on the 15th, armed.",
  "La 1re cohorte de la légion lombarde partira, le 15 du courant, avec armes et bagages, pour Vérone.",
  "Lombard legion's 1st cohort to Verona on the 15th, armed."),
 ("1796-11-03", 2, "Italy", "To Baraguey (Piave)", "italy-1796",
  "Enemy crossed the Piave: hurry every depot and draft.",
  "Nous sommes en présence de l'ennemi, qui a passé la Piave. Activez la marche de tous les dépôts.",
  "The enemy crossed the Piave: hurry every depot forward."),
 ("1797-02-02", 2, "Mantua", "Mantua capitulation", "campo-1797",
  "Wurmser's garrison marches out with war's honors: drums, colors. Granted.",
  "La garnison impériale de Mantoue et de la citadelle sortira par la porte majeure, avec les honneurs de la guerre, tambours battants, drapeaux déployés. — RÉPONSE. Accordé.",
  "Mantua's imperial garrison marches out the main gate with war's honors, drums beating, colors flying. — ANSWER. Granted."),
 ("1797-02-03", 2, "Faenza", "Romagna command", "campo-1797",
  "Rusca commands all Romagna, circulating conquest further.",
  "Le général de brigade Rusca commande toute la Romagne; il est chargé de faire circuler la conquête plus loin encore.",
  "Brigadier Rusca commands all Romagna, spreading conquest further."),
 ("1797-02-03", 2, "Italy", "To Leclerc (Russi/Ravenna)", "campo-1797",
  "Leclerc to Russi, then Ravenna on pacific signs; send inhabitants on.",
  "L'adjudant général Leclerc se rendra aujourd'hui à Russi, et de là à Ravenne, dès qu'il aura reconnu l'intention pacifique de ses habitants.",
  "Leclerc to Russi today, Ravenna on pacific signs."),
 ("1797-02-04", 2, "Forlì", "To Berthier (Mantua supply)", "campo-1797",
  "Victual Mantua a year for 12,000 men, 2,000 horse, drugs included.",
  "Ordre d'approvisionner Mantoue pour 12,000 hommes et 2,000 chevaux pendant un an, avec médicaments.",
  "Victual Mantua a year for 12,000 men and 2,000 horse, drugs included."),
 ("1797-02-06", 2, "Pesaro", "To Victor (Sinigaglia)", "campo-1797",
  "Avant-garde to Sinigaglia tomorrow; division from Pesaro at 5 a.m.",
  "Le général en chef ordonne au général Victor de porter demain son avant-garde à Sinigaglia.",
  "Victor's vanguard to Sinigaglia tomorrow."),
 ("1797-03-02", 3, "Mantua", "To Berthier (demolitions)", "campo-1797",
  "Cut all houses harming the fortress, per agreed plan.",
  "Donner l'ordre de faire couper toutes les maisons qui nuisent à la défense de la place.",
  "Cut every house harming the fortress's defence."),
 ("1797-03-05", 3, "Mantua", "To Corsica minister", "campo-1797",
  "Answering on Corsica's military state; Ca... commands.",
  "Je réponds à votre lettre relative à la situation militaire de la Corse.",
  "Answering your letter on Corsica's military state."),
 ("1797-03-05", 3, "Mantua", "Magazines declared", "campo-1797",
  "Mantua inhabitants declare all Austrian stores.",
  "Ordonnez à tous les habitants de Mantoue de déclarer tous les magasins appartenant aux Autrichiens.",
  "Mantuans declare all Austrian stores."),
 ("1797-03-06", 3, "Mantua", "Mantua ordinances", "campo-1797",
  "Houses razed, congregations regulated, gratifications listed.",
  "Bonaparte, général en chef de l'armée d'Italie, ordonne la démolition des maisons nuisibles.",
  "Mantua ordinances: razings, congregations, gratifications."),
 ("1797-05-02", 3, "Italy", "To Berthier (Venice manifesto)", "campo-1797",
  "A thousand printed copies of the Venice manifesto.",
  "Je vous envoie ci-joint un manifeste relatif aux Vénitiens, à imprimer à mille exemplaires.",
  "Enclosed Venice manifesto: print a thousand copies."),
 ("1797-05-06", 3, "Italy", "Venetian prisoners", "campo-1797",
  "Venetian soldiers to France, officers held.",
  "Vous donnerez ordre pour que tous les soldats vénitiens prisonniers soient transférés en France.",
  "Transfer all Venetian soldier-prisoners to France."),
 ("1797-05-06", 3, "Italy", "To a bishop", "campo-1797",
  "Your letter and prints received; the motto displeased me.",
  "J'ai reçu, Monsieur l'Évêque, votre lettre avec les deux imprimés. J'ai vu avec déplaisir la devise.",
  "Your letter and prints received, Bishop; the motto displeased me."),
 ("1797-05-06", 3, "Italy", "To the Directory (Corsica)", "campo-1797",
  "Corsican gendarmerie unpaid and risen for lack of funds.",
  "Il y a eu des troubles en Corse, occasionnés par l'insurrection de la gendarmerie, qui n'était pas payée.",
  "Corsica troubles: unpaid gendarmerie risen."),
 ("1797-05-06", 3, "Italy", "Livorno to Corsica", "campo-1797",
  "Livorno garrison embarked for Corsica within days.",
  "Je donne les ordres pour que la garnison de Livourne soit embarquée pour la Corse.",
  "Livorno's garrison embarks for Corsica within days."),
 ("1797-07-02", 3, "Mombello", "Lombardy proclamation", "campo-1797",
  "Lombardy independent; executive installed; seat left vacant.",
  "Vous trouverez ci-joint la proclamation relative à l'indépendance de la Lombardie.",
  "Enclosed: Lombardy independence proclamation."),
 ("1797-07-02", 3, "Mombello", "To the Directory (Naples)", "campo-1797",
  "Gallo showed Naples powers: Elba and Piombino offered for Levant isles.",
  "M. de Gallo m'a montré des pleins pouvoirs de Naples, offrant l'île d'Elbe contre les îles du Levant.",
  "Gallo showed Naples powers: Elba offered for the Levant isles."),
 ("1797-07-03", 3, "Mombello", "Antraigues letters", "campo-1797",
  "Intercepted Antraigues mail enclosed, No. I first.",
  "Vous trouverez ci-joint des lettres interceptées sur un courrier de M. d'Antraigues.",
  "Enclosed intercepted Antraigues mail."),
 ("1797-07-03", 3, "Mombello", "To Berthier (column)", "campo-1797",
  "Mobile column leaves Pavia the 18th, sleeps at Milan.",
  "La colonne mobile qui est à Pavie en partira le 18 pour coucher à Milan.",
  "Pavia mobile column marches the 18th, sleeps at Milan."),
 ("1797-07-05", 3, "Italy", "Venice marine", "campo-1797",
  "Inspect Venice marine impatiently; decide every hull's fate.",
  "J'attends avec impatience le résultat de l'inspection de la marine de Venise.",
  "Impatiently await the Venice marine inspection."),
 ("1797-09-02", 3, "Italy", "To Brueys?", "campo-1797",
  "Squadron news seen with pleasure; division reorganized.",
  "J'ai vu avec plaisir que Sa Majesté avait donné les ordres pour que la division fût réorganisée.",
  "Glad His Majesty ordered the division reorganized."),
 ("1797-09-02", 3, "Italy", "To Joseph (Pope)", "campo-1797",
  "Press Rome to recognize the Cisalpine, as Sardinia did.",
  "Je vous prie de faire expliquer la cour de Rome et de la porter à reconnaître la République cisalpine.",
  "Press Rome to recognize the Cisalpine Republic."),
 ("1797-09-02", 3, "Italy", "To Berthier (Venice)", "campo-1797",
  "5th line leaves Venice for Tortona; general follows.",
  "Donner l'ordre à la 5e demi-brigade de ligne, qui est à Venise, d'en partir pour Tortone.",
  "The 5th line leaves Venice for Tortona."),
 ("1797-09-03", 3, "Italy", "To the Directory (finances)", "campo-1797",
  "Finance minister's letter communicated; print it.",
  "J'ai l'honneur de vous communiquer la lettre au ministre des finances; je désirerais qu'on l'imprimât.",
  "Forwarding the finance minister's letter; print it."),
 ("1798-06-09", 4, "Off Malta", "To Brueys (convoy)", "egypt-1798",
  "Civita-Vecchia convoy to Malta roadstead orders.",
  "Vous prie de donner des ordres au convoi de Civita-Vecchia de se rendre devant le port de Malte.",
  "Order the Civita-Vecchia convoy before Malta port."),
 ("1798-06-09", 4, "Off Malta", "To Desaix (recon)", "egypt-1798",
  "Desaix by galley tonight along Malta's coast.",
  "Le général en chef ordonne au général Desaix de partir sur une des galères, pour parcourir ce soir la côte de Malte.",
  "Desaix reconnoitres Malta's coast tonight by galley."),
 ("1798-06-09", 4, "Off Malta", "Malta attack 9 p.m.", "egypt-1798",
  "9 p.m.: attack the island, execute orders punctually.",
  "Le général en chef, décidé à attaquer l'île de Malte, ordonne d'exécuter ponctuellement l'ordre.",
  "Malta attacked tonight: execute orders punctually."),
 ("1798-06-09", 4, "Off Malta", "To Reynier (Duprat)", "egypt-1798",
  "Duprat feeds Reynier's division meanwhile.",
  "Je donne des instructions au commissaire Duprat pour assurer la subsistance de votre division.",
  "Duprat instructed to feed your division meanwhile."),
 ("1798-06-09", 4, "Off Malta", "To Vaubois (2 a.m.)", "egypt-1798",
  "Vaubois ashore 2 a.m. somewhere along the coast.",
  "Il est ordonné au général Vaubois de partir le 22, à deux heures du matin, pour se rendre sur la côte.",
  "Vaubois lands 2 a.m. somewhere on the coast."),
 ("1798-07-02", 4, "Alexandria", "Alexandria proclamation", "egypt-1798",
  "Year 1213 of Hegira: the beys' hour of chastisement arrived.",
  "Depuis assez longtemps les beys qui gouvernent l'Égypte insultent à la nation française et couvrent ses négociants d'avanies: l'heure de leur châtiment est arrivée.",
  "Long enough have Egypt's beys insulted the French nation and heaped outrages on its merchants: their chastisement hour arrived."),
 ("1798-06-10", 4, "Off Malta", "Malta summons", "egypt-1798",
  "Eminence summoned aboard flagship to answer water plea.",
  "Éminence appelée à bord du vaisseau amiral pour répondre sur l'aiguade.",
  "Eminence summoned aboard flagship over watering rights."),
 ("1798-06-10", 4, "Off Malta", "Midnight landing", "egypt-1798",
  "Midnight: two 12-pounders ashore at Saint-Julien.",
  "À minuit, débarquer à la cale Saint-Julien deux pièces de 12.",
  "Midnight: land two 12-pounders at Saint-Julien."),
 ("1798-07-02", 4, "Alexandria", "Alexandria proclamation", "egypt-1798",
  "Year 1213 of Hegira: beys misgoverned long enough.",
  "Depuis assez longtemps les beys qui gouvernent l'Égypte insultent à la nation française.",
  "Long enough have Egypt's beys insulted the French nation."),
 ("1798-07-03", 4, "Alexandria", "Engineers council noon", "egypt-1798",
  "Tomorrow noon: engineers, artillery council at headquarters.",
  "Demain, à midi, il se tiendra un conseil chez le général du génie.",
  "Tomorrow noon: engineers-artillery council at headquarters."),
 ("1798-07-03", 4, "Alexandria", "Consuls' houses seized", "egypt-1798",
  "Every consul's house needed for the forces: seized.",
  "Toutes les maisons où se trouvent actuellement les consuls sont nécessaires pour les forces.",
  "All consuls' houses currently held are needed for the forces."),
 ("1798-07-03", 4, "Alexandria", "Alexandria arms order", "egypt-1798",
  "Every Alexandrian bears arms within 24 hours of publication.",
  "Tous les habitants d'Alexandrie seront tenus, vingt-quatre heures après publication, de porter les armes.",
  "Every Alexandrian armed within 24 hours of publication."),
 ("1798-12-02", 4, "Cairo", "To Marmont (secret)", "egypt-1798",
  "Secret meeting: Perrée, Dumanoir, Barré at your house.",
  "Vous ferez réunir chez vous, dans le plus grand secret, le contre-amiral Perrée et le capitaine Barré.",
  "Secret meeting at your house: Perrée, Dumanoir, Barré."),
 ("1798-12-03", 4, "Alexandria", "Sailors under 25", "egypt-1798",
  "Every convoy sailor under 25, all nations, drafted.",
  "J'ai donné ordre pour que tous les matelots du convoi ayant moins de vingt-cinq ans soient levés.",
  "Draft every convoy sailor under twenty-five, all nations."),
 ("1798-12-04", 4, "Cairo", "Bon at Birket", "egypt-1798",
  "Bon slept at Birket el-Hâggy with battalion, Moghrebins, guns.",
  "Le général Bon a couché hier à Birket el-Hâggy avec un bon bataillon et deux pièces de canon.",
  "Bon slept at Birket el-Hâggy with battalion and two guns."),
 ("1798-12-07", 4, "Cairo", "Copts protected", "egypt-1798",
  "The Coptic nation protected, never more debased.",
  "J'ai reçu la lettre que m'a écrite la nation copte. Elle ne sera plus avilie.",
  "The Coptic nation's letter received; never more debased."),
 ("1798-12-07", 4, "Giza", "Andréossy survey", "egypt-1798",
  "Survey Gizych province: villages, men of influence.",
  "Indépendamment du myry de la province de Gizych, connaître les villages et les hommes influents.",
  "Survey Gizych: villages and influential men."),
 ("1798-12-07", 4, "Cairo", "Boats must be paid", "egypt-1798",
  "None takes boats free; artillery pays for boats.",
  "Personne n'a le droit de prendre les bateaux; si l'artillerie en a besoin, qu'elle les paye.",
  "No free boats; artillery pays for boats."),
 ("1799-01-02", 4, "Cairo", "To the Divan", "egypt-1798",
  "Your letter read with the pleasure thinking of you gives.",
  "J'ai reçu la lettre que vous m'avez écrite; je l'ai lue avec plaisir. […]",
  "Your letter received and read with pleasure. […]"),
 ("1799-01-05", 4, "Cairo", "Guides at 5 a.m.", "egypt-1798",
  "Foot guides, 100 men of the 9th, one 3-pounder double-teamed at 5 a.m.",
  "Vous ferez partir demain, à cinq heures du matin, les guides à pied et 100 hommes de la 9e.",
  "Tomorrow 5 a.m.: foot guides and 100 of the 9th march."),
 ("1799-01-07", 4, "Cairo", "To Marmont (desert)", "egypt-1798",
  "Back from desert ride: your Frimaire-Nivôse letters approved.",
  "À mon retour d'une course dans le désert, je reçois vos lettres. J'approuve vos mesures.",
  "Back from desert ride: your letters and measures approved."),
 ("1799-01-07", 4, "Damietta", "To Digua (taxes)", "egypt-1798",
  "Press in every way the tax returns.",
  "Je vous prie d'activer, par tous les moyens possibles, la rentrée des contributions.",
  "Press tax returns by every possible means."),
 ("1799-01-08", 4, "Cairo", "Abou-Chayr beheaded", "egypt-1798",
  "Divan member of Qelyoub, convicted: the axe.",
  "Le général en chef a ordonné de faire couper la tête à Abou-Chayr, membre du divan, convaincu de trahison.",
  "Behead Abou-Chayr, divan member, convicted of treason."),
 ("1799-01-10", 4, "Cairo", "Dromedary regiment", "egypt-1798",
  "Maltese and nautical legions give 10 men each for dromedaries.",
  "La légion maltaise et la légion nautique fourniront chacune 10 hommes pour le régiment des dromadaires.",
  "Maltese and nautical legions give 10 men each for dromedaries."),
 ("1799-01-10", 4, "Cairo", "To Berthier (Revanche)", "egypt-1798",
  "Extremely displeased Menou kept the Revanche ordered to Damietta.",
  "Je suis extrêmement mécontent que le général Menou ait retenu la Revanche, qui avait ordre de se rendre à Damiette.",
  "Extremely displeased Menou kept the Revanche from Damietta."),
 ("1799-02-05", 5, "Cairo", "To Berthier (citadel)", "egypt-1798",
  "Write citadel and forts for their states.",
  "Vous voudrez bien écrire aux commandants de la citadelle et des forts pour qu'ils m'envoient leurs états.",
  "Write citadel and forts for their returns."),
 ("1799-02-05", 5, "Cairo", "To Dommartin (mortars)", "egypt-1798",
  "Six 6-inch mortars to Boulaq marine commander.",
  "Vous trouverez ci-joint l'ordre de mettre à votre disposition six pierriers de 6 pouces.",
  "Six 6-inch mortars placed at your disposal."),
 ("1799-02-10", 5, "Cairo", "Ragusan ship", "egypt-1798",
  "Ragusan entered Alexandria with Hamelin and Livron aboard.",
  "Un bâtiment ragusin est entré dans le port d'Alexandrie; il avait à bord les citoyens Hamelin et Livron.",
  "A Ragusan entered Alexandria with Hamelin and Livron aboard."),
 ("1799-02-14", 5, "Cairo", "To Caffarelli (wells)", "egypt-1798",
  "Engineer at once to El-Arich road wells, watch them.",
  "Donner l'ordre à un officier du génie de partir pour les puits de la route d'El-Arich.",
  "An engineer at once to the El-Arich road wells."),
 ("1799-02-14", 5, "Cairo", "To Murat (depart)", "egypt-1798",
  "Depart tomorrow 27th, 8 a.m. (order of the 26th).",
  "Il est ordonné au général Murat de partir demain, 27 du courant, à huit heures du matin.",
  "Murat departs tomorrow 27th at 8 a.m."),
 ("1799-02-15", 5, "Cairo", "To Kléber (march)", "egypt-1798",
  "Bon marches this morning; cavalry same place.",
  "Le général Bon part ce matin pour se rendre à la première journée. La cavalerie part aussi.",
  "Bon marches this morning; cavalry too."),
 ("1799-02-15", 5, "Cairo", "Qatyeh depot", "egypt-1798",
  "Pay chest, shoes, clothing all into Fort Qatyeh.",
  "Le payeur mettra sa caisse dans le fort de Qatyeh. Tous les souliers et effets d'habillement aussi.",
  "Pay chest, shoes and clothing all into Fort Qatyeh."),
 ("1799-03-04", 5, "Jaffa", "Straw order", "egypt-1798",
  "Troops burning camp straw and wood: rarest objects.",
  "Le général en chef voit avec peine que les troupes brûlent, en quittant leurs camps, la paille et le bois.",
  "Troops burning camp straw and wood on leaving: rarest objects."),
 ("1799-03-07", 5, "Jaffa", "To Abdallah (parley)", "egypt-1798",
  "God merciful: came to Palestine only to chase its tyrants.",
  "Dieu est clément et miséricordieux! Le général Bonaparte ne s'est porté en Palestine que pour en chasser les tyrans.",
  "God is clement and merciful! Bonaparte came to Palestine only to chase tyrants."),
 ("1799-03-09", 5, "Jaffa", "El-Arich recap", "egypt-1798",
  "30 Pluviôse: El-Arich after three days open trench, practicable breach.",
  "Le 30 pluviôse, le quartier général est à El-Arich. Ce fort s'est rendu après trois jours de tranchée ouverte.",
  "30 Pluviôse: El-Arich after three days open trench."),
 ("1799-03-09", 5, "Jaffa", "Egyptian company", "egypt-1798",
  "30–100 Egyptians taken at Jaffa into a company.",
  "Vous pouvez prendre 30 à 100 hommes parmi les Égyptiens pris à Jaffa, pour en faire une compagnie.",
  "Take 30–100 Egyptians at Jaffa for a company."),
 ("1799-03-09", 5, "Jaffa", "Séquestre order", "egypt-1798",
  "Sequester every magazine: Gontier to Jaffa for measures.",
  "Faire séquestrer tous les magasins; le citoyen Gontier ira à Jaffa pour les mesures.",
  "Sequester every magazine; Gontier to Jaffa."),
 ("1799-05-04", 5, "Acre", "To Rampon (sap)", "egypt-1798",
  "Scouts hold tonight's right sap, 8–9 p.m.",
  "Le général en chef ordonne que vos éclaireurs occupent ce soir, entre huit et neuf heures, le boyau de la droite.",
  "Scouts hold tonight's right sap, 8–9 p.m."),
 ("1799-05-09", 5, "Acre", "Lannes? tower", "egypt-1798",
  "Breach great tower untenable under Pharos fires.",
  "Le retranchement de la grande tour de brèche n'est plus tenable, à cause des feux du Pharos.",
  "Breach great tower untenable under Pharos fires."),
 ("1799-05-09", 5, "Acre", "To Murat (crest)", "egypt-1798",
  "Midnight: occupy second tower crest by the breach.",
  "Qu'à minuit vous fassiez occuper la crête de la seconde tour, qui tient à celle de brèche.",
  "Midnight: occupy the second tower crest."),
 ("1799-05-13", 5, "Acre", "To Lambert (Hayfa)", "egypt-1798",
  "22nd light with dromedaries to Hayfa authorized.",
  "Le général en chef vous autorise à partir avec la 22e légère et des dromadaires pour Hayfa.",
  "March the 22nd light with dromedaries to Hayfa."),
 ("1799-05-16", 5, "Acre", "Wounded to Jaffa", "egypt-1798",
  "400 wounded to Tantourah tomorrow morning.",
  "Faites filer, demain matin, 400 blessés sur Tantourah.",
  "Move 400 wounded to Tantourah tomorrow morning."),
 ("1799-05-16", 5, "Acre", "Wounded to frigates", "egypt-1798",
  "Wounded to Jaffa or frigates; Leturcq sends a convoy.",
  "Faites filer les blessés sur Jaffa ou sur les frégates.",
  "Move wounded to Jaffa or the frigates."),
 ("1799-05-17", 5, "Acre", "Desert order", "egypt-1798",
  "Crossed Africa–Asia desert faster than an Arab army.",
  "Soldats, vous avez traversé le désert qui sépare l'Afrique de l'Asie avec plus de rapidité qu'une armée arabe.",
  "Soldiers, you crossed the Africa–Asia desert faster than an Arab army."),
 ("1799-07-02", 5, "Cairo", "To Desaix (letters)", "egypt-1798",
  "Your 3 Messidor letter; Friant from Beny-Soueyf 12th.",
  "Je reçois, Citoyen Général, votre lettre du 3 messidor, et une du général Friant du 12.",
  "Your 3 Messidor letter received, and Friant's of the 12th."),
 ("1799-07-03", 5, "Cairo", "To Beynier (cavalry)", "egypt-1798",
  "Your El-Senytali letter; all army cavalry in Bahyreh now.",
  "J'ai reçu votre lettre d'El-Senytali. Toute la cavalerie de l'armée est dans le Bahyreh.",
  "Your El-Senytali letter received; all cavalry in Bahyreh."),
 ("1799-07-04", 5, "Cairo", "Qoseyr customs", "egypt-1798",
  "Qoseyr customs farmed out no more: Suez rules.",
  "L'affermage de la douane de Qoseyr ne peut exister: même organisation que Suez.",
  "Qoseyr customs farmed no more: Suez rules apply."),
 ("1799-07-05", 5, "Cairo", "To Desaix (Mourad)", "egypt-1798",
  "Friant: Mourad still at Hayàn fountain; drive him out.",
  "Le général Friant me mande que Mourad-Bey est toujours à la fontaine de Hayàn. Chassez-le.",
  "Friant: Mourad still at Hayàn fountain. Drive him out."),
 ("1799-07-07", 5, "Cairo", "To Lannes (intel)", "egypt-1798",
  "Your 19th received; Mourad never left Rayàn fountain.",
  "Je reçois votre lettre du 19; Mourad-Bey n'a pas bougé de la fontaine de Rayàn.",
  "Your 19th received; Mourad never left Rayàn fountain."),
 ("1799-07-09", 5, "Cairo", "To Friant (Mourad)", "egypt-1798",
  "Your two 18th received at once.",
  "Je reçois à l'instant vos deux lettres du 18.",
  "Both your 18th letters just received."),
 ("1799-07-09", 5, "Cairo", "To Desaix (Tali)", "egypt-1798",
  "Your two 14th from Talià received; gather a little.",
  "Je reçois vos deux lettres du 14, de Talià. Il faut réunir un peu.",
  "Your two 14th from Talià received; we must gather."),
 ("1799-08-02", 5, "Cairo", "To Digua (Aboukir)", "egypt-1798",
  "Aboukir fort, the enemy reserve in battle, surrendered.",
  "Le fort d'Aboukir, où l'ennemi avait sa réserve pendant la bataille, vient de se rendre.",
  "Aboukir fort, the enemy's battle reserve, surrendered."),
 ("1799-08-04", 5, "Cairo", "To the Directory (Aboukir)", "egypt-1798",
  "8 Thermidor: Aboukir summoned; pasha's son would capitulate.",
  "Le 8 thermidor, je fis sommer le château d'Aboukir. Le fils du pacha voulait capituler.",
  "8 Thermidor: Aboukir summoned; the pasha's son would yield."),
 ("1799-08-11", 5, "Cairo", "To Desaix (scolded)", "egypt-1798",
  "Little satisfied with all your operations in this movement.",
  "J'ai été peu satisfait de toutes vos opérations pendant le mouvement qui vient d'avoir lieu.",
  "Little satisfied with all your operations in this movement."),
 ("1799-08-11", 5, "Cairo", "To Desaix (paymaster)", "egypt-1798",
  "On Syria return you would pass 150,000 livres to the paymaster.",
  "Vous m'avez fait connaître, à mon retour de Syrie, que vous alliez faire passer 150,000 livres au payeur.",
  "On Syria return you would pass 150,000 livres to the paymaster."),
 ("1799-08-11", 5, "Cairo", "To Berthier (Zajonchek)", "egypt-1798",
  "Extremely displeased with Zajonchek's negligence in execution.",
  "Je suis extrêmement mécontent du général Zajonchek, qui a mis de la négligence dans l'exécution.",
  "Extremely displeased with Zajonchek's negligent execution."),
 ("1799-08-11", 5, "Cairo", "To Desaix (approves)", "egypt-1798",
  "Your 18 Thermidor received; projects fully approved.",
  "J'ai reçu votre lettre du 18 thermidor. J'approuve complètement les projets formés.",
  "Your 18 Thermidor received; projects fully approved."),
 ("1799-08-12", 5, "Cairo", "To Lannes (guides)", "egypt-1798",
  "Keep my guides and crews; Menouf business first.",
  "Je vous prie de garder mes guides et mes équipages.",
  "Keep my guides and crews."),
]

out = []
for iso, vol, loc, toline, eid, ctx, fr, en in REC:
    push(out, NAP, "Army of Italy" if iso < "1798" else "Army of the Orient", iso, None, loc,
         "“" + en + " […]”", f"{toline}, {iso}", ARCH, U(vol),
         "letter", ctx + TR, eid)
    out[-1]["originalText"] = fr
    out[-1]["originalLanguage"] = "French"

json.dump(out, open("data/nap_trancheB.json", "w"), ensure_ascii=False, indent=1)
print("trancheB:", len(out))
