#!/usr/bin/env python3
"""French bulk: PD Second Empire Correspondance + Chronicle's own English
translations (marked TRANSLATION, translator noted). Verbatim FR excerpts."""
import json, sys
sys.path.insert(0, "sources")
from common import push

NAP = {"author": "Napoleon Bonaparte", "handle": "@bonaparte", "accountType": "person"}
DIRN = {"author": "The Executive Directory", "handle": "@directoire", "accountType": "institution"}
ARCH = "Correspondance de Napoléon Ier, Second Empire ed. (Paris, 1858) — public domain (French)"
TR = " Translated for Chronicle from the public-domain French; original below."

def U(vol):
    return f"https://archive.org/details/correspondancede{vol:02d}napouoft"

# (iso, vol, loc, toline, author, eid, ctx, fr, en)
# NOTE: Dec 1797–Jan 1798 Paris letters live in build_france2.py — do not
# re-add them here (duplicate ids break the index build).
REC = [
 ("1799-04-02", 5, "Damietta", "To Murat (order)", NAP, "egypt-1798",
  "Safed castle holds neither Jordan nor Damascus road: staff appreciation.",
  "Par la description que vous lui donnez de ce lieu, il lui paraît clair que le château ne défend ni le passage du Jourdain, ni la route qui de Damas.",
  "By your description, the castle clearly commands neither the Jordan crossing nor the Damascus road."),
 ("1799-04-02", 5, "Damietta", "To Almeras", NAP, "egypt-1798",
  "A boat to Damietta with army news and artillery letters.",
  "J'expédie à Damiette un bâtiment pour vous donner des nouvelles de l'armée et porter des lettres du général Dommartin.",
  "I dispatch a vessel to Damietta with army news and General Dommartin's letters."),
 ("1799-04-05", 5, "Before Acre", "To Kléber", NAP, "egypt-1798",
  "Haifa's 25th men to Daoud's mill; detachments tonight.",
  "L'intention du général en chef est de faire venir de Haïfa tous les hommes de la 25e demi-brigade qui y sont, pour augmenter le poste du moulin de Daoud.",
  "The General-in-Chief will draw from Haifa all the 25th demi-brigade men there, to strengthen Daoud's mill post."),
 ("1799-04-05", 5, "Damietta", "To Almeras", NAP, "egypt-1798",
  "Second boat for fear the first miscarried: we need war munitions.",
  "Je vous ai expédié, le 13, un bateau avec un officier de marine, pour vous faire connaître le besoin que nous avons de munitions de guerre.",
  "On the 13th I sent a boat with a naval officer to tell you our need of war munitions."),
 ("1799-04-09", 5, "Before Acre", "To Kléber", NAP, "egypt-1798",
  "Light infantry to Nazareth via Chafa-Amr, at once.",
  "Le général en chef ordonne que vous fassiez partir sur-le-champ toute votre infanterie légère, pour se rendre à Nazareth.",
  "The General-in-Chief orders all your light infantry to march at once for Nazareth."),
 ("1799-04-10", 5, "Before Acre", "To Larrey, surgeon", NAP, "egypt-1798",
  "A health officer daily in the trench, at its tail.",
  "Ordre au citoyen Larrey d'envoyer chaque jour un officier de santé pour être de service à la tranchée.",
  "Citizen Larrey will send daily a health officer to serve in the trench."),
 ("1799-04-13", 5, "Before Acre", "To Larrey", NAP, "egypt-1798",
  "Tomorrow 3 a.m.: 4th light and 25th minus Daoud's men.",
  "Le général en chef vous ordonne de partir demain, à trois heures du matin, avec la 4e demi-brigade légère.",
  "The General-in-Chief orders you to march tomorrow at 3 a.m. with the 4th light demi-brigade."),
 ("1799-04-15", 5, "Before Acre", "To Gen. Bon", NAP, "egypt-1798",
  "Bon to Nazareth–Soulyn gap, link with Kléber.",
  "Le général en chef ordonne au général Bon de partir sur-le-champ pour prendre position entre Nazareth et le village de Soulyn.",
  "General Bon will march at once to take position between Nazareth and Soulyn village."),
 ("1799-04-18", 5, "Before Acre", "Order of the day", NAP, "egypt-1798",
  "Nazareth and Saron: Djezzar's relief army completely beaten.",
  "Les janissaires de Damas réunis à la cavalerie de Djezzar ont passé le Jourdain dans l'intention de faire lever le siège d'Acre; ils ont été complètement battus aux combats de Nazareth.",
  "Damascus janissaries with Djezzar's cavalry crossed the Jordan to raise Acre's siege; they were completely beaten at Nazareth."),
 ("1799-04-19", 4, "Genoa", "To Baraguey d'Hilliers", NAP, "egypt-1798",
  "Sail Genoa–Toulon 6–7 Floréal with casualty returns.",
  "Il est ordonné au général Baraguey d'Hilliers de lever l'ancre de Gênes, si le temps le permet, le 6 floréal ou au plus tard le 7.",
  "General Baraguey d'Hilliers will weigh from Genoa, weather permitting, on 6 or at latest 7 Floréal."),
 ("1799-06-02", 5, "Egypt", "To Gen. Robin", NAP, "egypt-1798",
  "Soup, water, rest at Mesoudyah, then midnight march.",
  "Le général Robin partira aujourd'hui à midi pour se rendre à Mesoudyah, où il restera assez de temps pour que sa troupe fasse la soupe, sa provision d'eau et se repose.",
  "General Robin marches today at noon for Mesoudyah, resting long enough for soup, water and rest."),
 ("1799-06-02", 5, "Egypt", "To Berthier", NAP, "egypt-1798",
  "Acre and Jaffa Christians sheltered two days at Qatyeh.",
  "Vous voudrez bien donner l'ordre de laisser à Qatyeh tous les chrétiens qui se sont réfugiés, soit d'Acre, soit de Jaffa, auprès de nous.",
  "Leave at Qatyeh all Christians sheltered with us from Acre or Jaffa."),
 ("1799-06-02", 5, "El-Arich", "To Berthier", NAP, "egypt-1798",
  "El-Arich garrisoned: sappers, smiths, fifty gunners.",
  "Le 1er bataillon de la 3e tiendra garnison, jusqu'à nouvel ordre, dans le fort d'El-Arich.",
  "The 3rd's 1st battalion garrisons Fort El-Arich until further orders."),
 ("1799-06-15", 5, "Egypt", "Order of the day", NAP, "egypt-1798",
  "Dugua thanked: Egypt tranquil through Syria thanks to him.",
  "Le général en chef témoigne sa satisfaction au général Dugua de la conduite qu'il a tenue pendant son absence en Syrie.",
  "The General-in-Chief thanks General Dugua for his conduct during the Syria absence."),
 ("1799-06-15", 5, "Egypt", "To Desaix", NAP, "egypt-1798",
  "Back yesterday; Kléber at Damietta; printed relations hold the truth.",
  "Je suis arrivé ici hier avec une partie de l'armée. J'ai laissé une bonne garnison dans le fort d'El-Arich.",
  "I arrived yesterday with part of the army. I left a good garrison in Fort El-Arich."),
 ("1799-06-17", 5, "Cairo", "To Marmont", NAP, "egypt-1798",
  "Desaix to Rahyreh province with nautical legion via Rosetta.",
  "Le général Desaix se rend dans la province de Rahyreh avec un bataillon; mon intention est que la légion nautique en parte de Rosette.",
  "General Desaix goes to Rahyreh province; the nautical legion will leave Rosetta."),
 ("1799-06-19", 5, "Cairo", "To Desaix", NAP, "egypt-1798",
  "Qoseyr occupied with pleasure; engineers sent for Upper Egypt works.",
  "J'ai appris avec plaisir votre occupation de Qoseyr. Je donne ordre qu'on vous envoie plusieurs officiers du génie.",
  "I learned with pleasure your occupation of Qoseyr. Engineers are ordered to you."),
 ("1799-06-21", 5, "Cairo", "To Sanson", NAP, "egypt-1798",
  "Citadel inspected in person; Fauvi oversteps with the commandant.",
  "J'ai visité hier la citadelle du Caire; je me suis convaincu par moi-même que le citoyen Fauvi prend envers le commandant un ton qui n'est pas convenable.",
  "Yesterday I inspected Cairo citadel myself; Citizen Fauvi takes an improper tone with the commandant."),
 ("1799-06-22", 5, "Cairo", "Order of the day", NAP, "egypt-1798",
  "Dupas praised: prodigious activity, best possible defence.",
  "Le général en chef a inspecté les fortifications de la citadelle; il a été satisfait de l'activité prodigieuse du chef de brigade Dupas.",
  "The General-in-Chief inspected the citadel works; Brigade Chief Dupas's prodigious activity satisfies him."),
 ("1799-06-23", 5, "Cairo", "To Kléber", NAP, "egypt-1798",
  "Hassan-Toubar leaves his thirty-year-old son hostage tonight.",
  "Hassan-Toubâr sort de chez moi. Il remet ici, ce soir, son fils en otage; c'est un homme âgé de trente ans.",
  "Hassan-Toubar leaves me. Tonight he hands over his son as hostage, a man of thirty."),
 ("1800-01-02", 6, "Paris", "Décision", NAP, "consulate-1802",
  "Paris National Guard reorganisation debated in Council.",
  "Renvoyé à la section de l'intérieur un projet de règlement pour la réorganisation de la garde nationale parisienne.",
  "Referred to the interior section: draft rules reorganising the Paris National Guard."),
 ("1800-01-04", 6, "Paris", "Arrêté Dupuy", NAP, "consulate-1802",
  "Dupuy died commanding the 32nd through five campaigns: honored.",
  "Considérant que le chef de brigade Dupuy, mort les armes à la main au Caire, a commandé pendant cinq campagnes la 32e demi-brigade.",
  "Whereas Brigade Chief Dupuy, dead arms in hand at Cairo, commanded the 32nd through five campaigns."),
 ("1800-01-04", 6, "Paris", "To Saint-Hilaire", NAP, "consulate-1802",
  "Parties are over: enlighten the people, set everything in motion.",
  "Je suis satisfait de la conduite que vous tenez dans la 8e division. Éclairez le peuple, faites sentir à tous les citoyens que le temps des partis et des déchirements est passé.",
  "I am satisfied with your conduct in the 8th division. Enlighten the people; let all citizens feel that parties and strife are past."),
 ("1800-01-05", 6, "Paris", "To Bacher (Pichegru)", NAP, "consulate-1802",
  "Truth not calumny: what did Pichegru do abroad since Fructidor?",
  "Je suis chargé de vous demander quelle a été la conduite de Pichegru en pays étranger, depuis le 18 fructidor an V. C'est la vérité qu'on veut connaître, et non la calomnie.",
  "Tell me Pichegru's conduct abroad since 18 Fructidor Year V. Truth is wanted, not calumny."),
 ("1800-01-05", 6, "Paris", "To Hédouville (Brest)", NAP, "consulate-1802",
  "15,000 men demanded and more: courier extraordinary.",
  "Vous avez demandé 15,000 hommes. Le Consul Bonaparte vient de recevoir votre lettre et me charge de vous écrire par courrier extraordinaire.",
  "You asked 15,000 men. Consul Bonaparte charges me to answer by extraordinary courier."),
 ("1800-01-08", 6, "Paris", "To Guidal (chouans)", NAP, "consulate-1802",
  "Chouan bands in Orne: what are you doing, what are your troops doing?",
  "Des rassemblements de chouans existent dans le département de l'Orne. Le Premier Consul se plaint de n'avoir pas encore entendu parler de vous.",
  "Chouan bands gather in Orne. The First Consul complains of hearing nothing from you."),
 ("1800-01-08", 6, "Paris", "To Berthier (habillement)", NAP, "consulate-1802",
  "Report at once: clothing, linen, shoes, harness administration.",
  "Le ministre de la guerre me fera connaître le plus tôt possible l'état actuel de l'administration de l'habillement.",
  "The war minister will report at once the clothing administration's state."),
 ("1800-01-09", 6, "Paris", "To Lefebvre (chouans)", NAP, "consulate-1802",
  "Chouans at Saint-Jean: indignation that Ramefroy's letter sufficed.",
  "Le Premier Consul a vu avec indignation qu'on ait laissé établir les chouans à Saint-Jean de Margon.",
  "The First Consul saw with indignation chouans settled at Saint-Jean de Margon."),
 ("1800-01-09", 6, "Paris", "To Berthier (Gardanne)", NAP, "consulate-1802",
  "England army officers to embark by the 24th, no delay.",
  "Vous ordonnerez sur-le-champ au général de division Gardanne et aux autres officiers de l'armée d'Angleterre d'être rendus le 24 du courant.",
  "Order General Gardanne and all England-army officers embarked by the 24th."),
 ("1802-02-02", 7, "Paris", "To Lebrun (Turin)", NAP, "consulate-1802",
  "Night courier via Turin, Bologna, Rome: letters by hand.",
  "Le citoyen Lebrun partira cette nuit; il se rendra à Turin, où, sans s'arrêter, il fera remettre la lettre ci-jointe au général Jourdan.",
  "Citizen Lebrun leaves tonight for Turin, delivering the enclosed to General Jourdan without stopping."),
 ("1802-02-02", 7, "Paris", "To the Pope", NAP, "consulate-1802",
  "Cisalpine arranged: Catholic religion recognised, first article.",
  "Je m'empresse de faire connaître à Votre Sainteté que les affaires de la République cisalpine viennent d'être arrangées.",
  "I hasten to tell Your Holiness the Cisalpine Republic's affairs are arranged."),
 ("1802-02-02", 7, "Paris", "To Naples", NAP, "consulate-1802",
  "Sicily's welcome to 300 French thanked directly.",
  "Le général Silly m'a fait connaître l'accueil que Votre Majesté a fait aux 300 Français que les événements de la mer ont forcés de débarquer en Sicile.",
  "General Silly reports Your Majesty's welcome to 300 French forced by sea onto Sicily."),
 ("1802-02-02", 7, "Paris", "To Joseph (Amiens)", NAP, "consulate-1802",
  "Eight days more or less now indifferent at Amiens.",
  "Je reçois votre lettre du 12 pluviôse. Il paraît que tout marche à Amiens. Huit jours plus tôt ou huit jours plus tard sont actuellement indifférents.",
  "Your 12 Pluviôse letter received. All moves at Amiens. Eight days more or less are now indifferent."),
 ("1802-02-05", 7, "Paris", "Décision promotions", NAP, "consulate-1802",
  "No hussar majority without two years' grade.",
  "Le ministre de la guerre propose de confirmer le citoyen Fournier dans le grade de chef d'escadron au 12e hussards, n'ayant pas deux ans de grade.",
  "The minister proposes confirming Fournier's hussar majority, lacking two years' grade."),
 ("1802-02-06", 7, "Paris", "Arrêté Egypt science", NAP, "consulate-1802",
  "Egypt's science published at Government expense.",
  "Article 1er. — Les mémoires, plans, dessins et généralement tous les résultats relatifs aux sciences et arts, obtenus pendant le cours de l'expédition d'Égypte, seront publiés aux frais du Gouvernement.",
  "Article 1. — Memoirs, plans, drawings, all science and arts results of the Egypt expedition, shall be published at Government expense."),
 ("1802-02-07", 7, "Paris", "To Lauriston (Brest)", NAP, "consulate-1802",
  "Wait at Brest for Bouvet's squadron: 3,000 men for Gobert.",
  "Le citoyen Lauriston se rendra à Brest; il y restera jusqu'à ce que l'escadre du contre-amiral Bouvet soit partie.",
  "Citizen Lauriston goes to Brest, waiting Bouvet's squadron's sailing."),
 ("1802-02-10", 7, "Paris", "To Lucca", NAP, "consulate-1802",
  "Small state, live tranquil: beware factional spirit.",
  "J'ai lu avec plaisir que vous étiez définitivement constitués. Vous êtes un petit État; vivez tranquilles; défendez-vous de l'esprit de faction.",
  "Glad to read you firmly constituted. You are a small state; live tranquil; shun faction."),
 ("1802-12-02", 8, "Paris", "Piedmont bishops note", NAP, "consulate-1802",
  "Six bishops suffice Piedmont, endowed with all Church goods.",
  "Il est instant d'arranger les affaires ecclésiastiques du Piémont. S'il n'y a en France qu'un évêque par deux départements, il n'y a pas d'inconvénient à laisser en Piémont six évêques.",
  "Piedmont's church affairs need settling. If France has a bishop per two departments, six may stay in Piedmont."),
 ("1802-12-02", 8, "Paris", "To Gaudin (bois)", NAP, "consulate-1802",
  "Wood-cuttings as paper money: 100 to 10,000 francs.",
  "Le Premier Consul désire que vous fassiez un rapport sur les traites de coupes de bois à organiser comme papier-monnaie.",
  "Report on wood-cutting bills as paper money."),
 ("1802-12-02", 8, "Paris", "To Marbois (bois)", NAP, "consulate-1802",
  "Wood revenues split Year XI/XII by month of falling due.",
  "Mon intention est de n'affecter au service de l'an XI, sur la coupe des bois, que les payements qui échoient en germinal et en messidor.",
  "Only germinal/messidor wood payments fund Year XI; the rest Year XII."),
 ("1802-12-02", 8, "Paris", "To Talleyrand (Ruffin)", NAP, "consulate-1802",
  "Djezzar seized Ruffin's rich ship: demand it back at once.",
  "Je vous prie de faire connaître au général Brune qu'il ait à réclamer que le bâtiment du citoyen Ruffin, confisqué par Djezzar-Pacha, lui soit sur-le-champ restitué.",
  "Tell General Brune to demand instant restitution of Citizen Ruffin's ship, seized by Djezzar-Pasha."),
 ("1802-12-04", 8, "Paris", "To Duroc (press)", NAP, "consulate-1802",
  "Beauvoisin gets the Ambigu plus Ivernois pamphlet: write up England.",
  "Le citoyen Duroc fera connaître au citoyen Beauvoisin qu'il m'adresse tout ce qu'il a de l'Ambigu, ainsi que le pamphlet d'Ivernois.",
  "Duroc gives Beauvoisin all his Ambigu plus the Ivernois pamphlet."),
 ("1802-12-07", 8, "Paris", "Island prisons", NAP, "consulate-1802",
  "Ré, Oléron, Sainte-Marguerite organised for deportees.",
  "Il est indispensable d'organiser aux îles de Ré, d'Oléron et Sainte-Marguerite, des prisons pour y renfermer tous les individus condamnés à la déportation.",
  "Ré, Oléron and Sainte-Marguerite must hold all sentenced deportees."),
 ("1802-12-10", 8, "Paris", "To Swiss deputies", NAP, "consulate-1802",
  "Switzerland critical: moderation, prudence, sacrifice of passions.",
  "Citoyens Députés, la situation de votre patrie est critique. La modération, la prudence et le sacrifice de vos passions sont nécessaires pour la sauver.",
  "Deputies, your fatherland is critical. Moderation, prudence, sacrificed passions alone can save it."),
 ("1802-12-10", 8, "Paris", "To Berthier (coasts)", NAP, "consulate-1802",
  "Plans for Quiberon, Belle-Île, Marcouf, Boulogne works.",
  "Je vous prie de donner ordre de dresser des plans pour mettre le fort Quiberon, la place de Belle-Île et les batteries de Boulogne en état.",
  "Order plans for Quiberon, Belle-Île and Boulogne batteries."),
 ("1803-02-03", 8, "St Cloud", "To Lebrun (pensions)", NAP, "consulate-1802",
  "'Liquidation of newly created pensions' means nothing: explain.",
  "Je vous prie de prendre connaissance du rapport ci-joint. Je ne conçois pas ce que veut dire ce mot de liquidation des pensions nouvellement créées.",
  "Read the enclosed report. 'Liquidation of newly created pensions' means nothing to me."),
 ("1803-02-03", 8, "Paris", "To Decrès (colonies)", NAP, "consulate-1802",
  "Havre, Dunkerque, Toulon, Genoa, Corsica sail together.",
  "Les 1,200 hommes qui sont partis du Havre, ceux prêts à partir de Dunkerque, les trois expéditions parties de Toulon feront arriver à la fois un assez grand nombre de troupes.",
  "The 1,200 sailed from Havre, Dunkerque ready, three Toulon expeditions: troops arriving together."),
 ("1803-02-04", 8, "Paris", "To Rochambeau", NAP, "consulate-1802",
  "Fort Dauphin retaken with pleasure: full confidence, vigorous measures approved.",
  "J'ai vu avec plaisir la reprise du fort Dauphin; je veux directement vous assurer de l'entière confiance que le Gouvernement a en vous.",
  "Glad of Fort Dauphin retaken; take directly my full confidence and approval of vigorous measures."),
 ("1803-02-05", 8, "Paris", "To Decrès (Saint-Domingue)", NAP, "consulate-1802",
  "15,000 men shipped; combine now a 6,500 expedition.",
  "Quinze mille hommes viennent ou vont finir d'être expédiés à Saint-Domingue. Mais il faut combiner, dès aujourd'hui, une expédition de 6,500 hommes.",
  "Fifteen thousand men shipped or shipping to Saint-Domingue. Combine now a 6,500 expedition."),
 ("1803-02-08", 8, "St Cloud", "To Berthier (Brisgau)", NAP, "consulate-1802",
  "Two Austrian companies into Brisgau: no obstacle.",
  "Je vous prie d'ordonner au commandant dans le Brisgau de recevoir deux compagnies de troupes autrichiennes.",
  "Order the Brisgau commander to receive two Austrian companies."),
 ("1803-02-08", 8, "Paris", "To Haüy", NAP, "consulate-1802",
  "The great mineralogist to write the lycées' math textbook.",
  "La confiance que j'ai dans vos grands talents me porte à désirer que vous vous chargiez de faire un ouvrage élémentaire pour la classe de mathématiques des Lycées nationaux.",
  "My trust in your great talents bids me ask an elementary mathematics work for the national lycées."),
 ("1803-02-09", 8, "Paris", "Télémaque mayor of Cap", NAP, "consulate-1802",
  "Black mayor thanks and devotion: recommend this brave nègre.",
  "Le nègre Télémaque remercie le Premier Consul de l'avoir nommé maire du Cap. Il proteste de son dévouement à la République.",
  "The nègre Télémaque thanks the First Consul for the Cap mayoralty, protesting devotion to the Republic."),
 ("1803-02-10", 8, "Paris", "To Régnier (Staël)", NAP, "consulate-1802",
  "Staël forbidden Paris, arrives at Melun: turn her back at once.",
  "Je suis instruit que madame de Staël, malgré la défense qui lui a été faite de venir à Paris, arrive le 20 à Melun. Donnez ordre de la faire sur-le-champ rétrograder.",
  "Madame de Staël, forbidden Paris, reaches Melun the 20th. Order police to turn her straight back."),
]

out = []
VOLM = {1797: 3, 1798: 3, 1799: 5, 1800: 6, 1802: 7, 1803: 8}
for iso, vol, loc, toline, who, eid, ctx, fr, en in REC:
    push(out, who, "Consulate", iso, None, loc, "“" + en + " […]”",
         f"{toline}, {iso}", ARCH, U(vol),
         "letter", ctx + TR, eid)
    out[-1]["originalText"] = fr
    out[-1]["originalLanguage"] = "French"

json.dump(out, open("data/nap_france_bulk.json", "w"), ensure_ascii=False, indent=1)
print("france bulk:", len(out))
