#!/usr/bin/env python3
"""1801: Consulate administration in French + own translations."""
import json, sys
sys.path.insert(0, "sources")
from common import push

NAP = {"author": "Napoleon Bonaparte", "handle": "@bonaparte", "accountType": "person"}
ARCH = "Correspondance de Napoléon Ier, Second Empire ed. (Paris, 1858), Vols. VI–VII — public domain (French)"
TR = " Translated for Chronicle from the public-domain French; original below."
U6 = "https://archive.org/details/correspondancede06napouoft"
U7 = "https://archive.org/details/correspondancede07napouoft"

# (iso, url, loc, toline, eid, ctx, fr, en)
REC = [
 ("1801-01-02", U6, "Paris", "Message au Corps législatif", "consulate-1802",
  "Hohenlinden resounds through Europe.",
  "Législateurs, la République triomphe. La victoire de Hohenlinden a retenti dans toute l'Europe.",
  "Legislators, the Republic triumphs. Hohenlinden's victory resounded through Europe."),
 ("1801-01-04", U6, "Paris", "Arrêté Tallien", "consulate-1802",
  "Tallien arrested for quitting Egypt without passport.",
  "Le ministre de la marine fera mettre en arrestation le citoyen Tallien, prévenu d'avoir quitté l'Égypte sans passe-port.",
  "The navy minister shall arrest Citizen Tallien, charged with quitting Egypt without passport."),
 ("1801-01-07", U6, "Paris", "To Talleyrand (Portugal)", "consulate-1802",
  "Spain pressed to make Portugal act against England.",
  "Je vous prie de remettre à M. de Muzquiz une lettre dans laquelle vous vous plaindrez des changements dans les préparatifs contre le Portugal.",
  "Hand M. de Muzquiz a letter complaining of changed preparations against Portugal."),
 ("1801-01-07", U6, "Paris", "To Berthier (Menou)", "consulate-1802",
  "Aboukir the only serious landing: warn Menou.",
  "Je désire que vous écriviez au général Menou, pour lui faire connaître qu'un débarquement en Égypte ne peut avoir sérieusement lieu qu'à Aboukir.",
  "Write General Menou that no serious Egypt landing can happen but at Aboukir."),
 ("1801-01-09", U6, "Paris", "To Moreau (3 Nivôse)", "consulate-1802",
  "Thanks for Hohenlinden — and the infernal machine survived.",
  "Je vous remercie de ce que vous me dites sur l'événement extraordinaire du 3 nivôse.",
  "I thank you for your news of the extraordinary 3 Nivôse event."),
 ("1801-01-09", U6, "Paris", "To Forfait (officers)", "consulate-1802",
  "Forty men from Bicêtre to Orléans to Nantes, then by sea.",
  "Quarante individus partent demain de Bicêtre pour Orléans, et de là se rendront à Nantes, où ils seront embarqués.",
  "Forty men leave Bicêtre tomorrow for Orléans, thence to embark at Nantes."),
 ("1801-01-13", U6, "Paris", "To Murat (Tuscany)", "consulate-1802",
  "Brune put Tuscany under Murat: wise confidence.",
  "La mesure prise par le général Brune, de mettre la Toscane sous vos ordres, me paraît extrêmement sage.",
  "Brune putting Tuscany under your orders seems to me extremely wise."),
 ("1801-01-14", U6, "Paris", "Ajaccio water", "consulate-1802",
  "Ajaccio may sell lands for water; old forts demolished.",
  "Une loi va autoriser la commune d'Ajaccio à vendre une partie de ses biens pour se procurer de l'eau.",
  "A law will let Ajaccio sell lands to bring water."),
 ("1801-01-14", U6, "Paris", "Secret instructions (Saint-Domingue)", "consulate-1802",
  "Combis mission: remind Spanish Santo Domingo it is French.",
  "Le principal but de la mission du citoyen Combis à Saint-Domingue est de faire souvenir aux habitants que ce pays est désormais français.",
  "Combis's mission: remind Santo Domingo's people the land is now French."),
 ("1801-01-14", U6, "Paris", "Instructions (Toussaint)", "consulate-1802",
  "Toussaint praised: prudence and courage saved the colony.",
  "Le général Toussaint Louverture, au milieu des orages de la révolution, est parvenu, par sa prudence et son courage, à sauver à la France une grande colonie.",
  "General Toussaint Louverture, amid revolutionary storms, saved France a great colony by prudence and courage."),
 ("1801-01-19", U6, "Paris", "To Talleyrand (Valais)", "consulate-1802",
  "Valais to the Léman department: treaty with Helvetia.",
  "Je vous prie de préparer un projet de traité avec l'Helvétie, pour qu'elle nous cède tout le Valais jusqu'à Brigg.",
  "Draft a treaty for Helvetia to cede all Valais to Brigg."),
 ("1801-01-21", U6, "Paris", "To Joseph (Russia)", "consulate-1802",
  "A friendly Russian letter in fifteen days: Paul melts.",
  "Hier est arrivé de Russie un courrier qui a fait la route en quinze jours; il m'a apporté une lettre extrêmement amicale.",
  "Yesterday a Russian courier arrived in fifteen days with an extremely friendly letter."),
 ("1801-02-04", U7, "Paris", "To Talleyrand (Murat/Rome)", "consulate-1802",
  "Night courier to Murat at Foligno: Rome instructions.",
  "Je vous prie d'expédier dans la nuit un courrier au général Murat, qui arrive demain à Foligno.",
  "Dispatch a night courier to General Murat, reaching Foligno tomorrow."),
 ("1801-03-02", U7, "Paris", "To Talleyrand (Madrid)", "consulate-1802",
  "Spain must make its navy act: recapitulatory dispatch.",
  "Expédiez un courrier à l'ambassadeur à Madrid; vous lui récapitulerez le grand intérêt que j'attache à voir les Espagnols reprendre de l'activité.",
  "Send Madrid the great interest I take in Spain's navy acting again."),
 ("1801-03-02", U7, "Paris", "To Savary (Lorient)", "consulate-1802",
  "Savary rides post-haste to Lorient for the Anacreon.",
  "Le chef de brigade Savary partira en toute diligence pour se rendre à Lorient.",
  "Brigade Chief Savary rides post-haste to Lorient."),
 ("1801-04-02", U7, "Paris", "To Gaudin (comptes)", "consulate-1802",
  "Military accountants differ considerably: report.",
  "Les Consuls voient avec peine qu'il existe des différences considérables dans les comptes des divisions militaires.",
  "The Consuls regret considerable differences in military accountants' books."),
 ("1801-05-03", U7, "Paris", "Décision (Georges)", "consulate-1802",
  "Georges's band seeks submission: hear them.",
  "Plusieurs individus de la bande de Georges témoignent le désir de se soumettre.",
  "Several of Georges's band wish to submit."),
 ("1801-05-04", U7, "Paris", "Arrêté (Brest garrison)", "consulate-1802",
  "Battalions to Brest: 30th light, 31st, 71st, 77th, 79th.",
  "Le ministre de la guerre donnera les ordres pour réunir à Brest un bataillon de la 30e légère, un de la 31e, un de la 71e.",
  "The war minister gathers battalions at Brest."),
 ("1801-06-02", U7, "Paris", "To Talleyrand (Moncey)", "consulate-1802",
  "Moncey commands French troops in Cisalpine: notify by express.",
  "Faites connaître par un courrier extraordinaire que le général Moncey est nommé commandant des troupes françaises dans la Cisalpine.",
  "Notify by express that Moncey commands French troops in Cisalpine."),
 ("1801-07-02", U7, "Paris", "Ligurian constitution", "consulate-1802",
  "Doge and podestat beat other titles for Liguria.",
  "Faites-lui connaître: 1° Que les mots doge, podestat sont meilleurs que les autres titres proposés.",
  "Tell him: 'doge' and 'podestat' suit Liguria better."),
 ("1801-07-04", U7, "Paris", "To Berthier (Livorno)", "consulate-1802",
  "Bravoure, Carrère, Succès frigates to cruise from Livorno.",
  "Faites connaître au général Murat que les frégates la Bravoure, la Carrère et le Succès doivent être arrivées à Livourne.",
  "Tell Murat the frigates Bravoure, Carrère, Succès reached Livorno for cruising."),
 ("1801-08-06", U7, "Paris", "To Fouché (press)", "consulate-1802",
  "Journalists forbidden to touch religion.",
  "Faites connaître aux journalistes, tant politiques que littéraires, qu'ils doivent s'abstenir de parler de tout ce qui peut concerner la religion.",
  "Tell journalists, political and literary, to abstain from all religious matter."),
 ("1801-08-06", U7, "Paris", "To Forfait (Brest)", "consulate-1802",
  "Levavasseur to Brest: extraordinary coast-battery inspection.",
  "Je vous prie de donner l'ordre au général Levavasseur de se rendre en poste à Brest pour l'inspection des batteries de côtes.",
  "Send Levavasseur post to Brest to inspect coast batteries."),
 ("1801-09-05", U7, "Paris", "To Berthier (Year X army)", "consulate-1802",
  "Redo the Year X organisation keeping all pay rates.",
  "Je vous prie de me refaire l'organisation de l'armée pour l'an X, en laissant partout les mêmes appointements.",
  "Redo the Year X army organisation at unchanged pay."),
 ("1801-09-05", U7, "Paris", "To Dumas", "consulate-1802",
  "Committee observations unreasonable; draft near the mark.",
  "J'ai lu les observations du comité; il n'y a rien de raisonnable.",
  "I read the committee's observations; nothing reasonable in them."),
 ("1801-10-03", U7, "Paris", "To Marbois (salines)", "consulate-1802",
  "Salines receipts of Years VIII–IX: warn the farmers-general.",
  "J'ai reçu l'état des recettes faites sur les salines. Il est nécessaire de faire connaître aux régisseurs que le Gouvernement veille.",
  "I have the salines' receipts. Warn the farmers the Government watches."),
 ("1801-10-04", U7, "Paris", "Théophilanthropes banned", "consulate-1802",
  "No more meetings in national buildings.",
  "Article 1er. — Les sociétés connues sous le nom de théophilanthropes ne pourront plus se réunir dans les édifices nationaux.",
  "Article 1. — Théophilanthrope societies shall no longer meet in national buildings."),
 ("1801-10-06", U7, "Paris", "Saber model", "consulate-1802",
  "Model a handy medium saber.",
  "Faites faire un modèle d'un sabre de dimensions médiocres et commodes.",
  "Have a handy medium saber modelled."),
 ("1801-11-08", U7, "Paris", "Saint-Domingue proclamation", "consulate-1802",
  "All French, all free, all equal before God and Republic.",
  "Habitants de Saint-Domingue, quelles que soient votre origine et votre couleur, vous êtes tous Français; vous êtes tous libres et tous égaux devant Dieu et devant la République.",
  "Saint-Domingue's people, whatever origin or color, are all Frenchmen, all free, all equal before God and Republic."),
 ("1801-11-09", U7, "Paris", "Peace proclamation", "consulate-1802",
  "Peace entire at last, earned by generous efforts.",
  "Français, vous l'avez enfin tout entière cette paix que vous avez méritée par de si longs et si généreux efforts!",
  "Frenchmen, yours at last entire, this peace earned by such long generous efforts!"),
 ("1801-12-02", U7, "Paris", "To Berthier (Helvetia)", "consulate-1802",
  "Montchoisy told: Paris disowns the Helvetic government.",
  "Vous ferez connaître au général Montchoisy que le Gouvernement ne reconnaît point le Gouvernement helvétique.",
  "Tell Montchoisy Paris disowns the Helvetic government."),
 ("1801-12-04", U7, "Paris", "Volta gratification", "consulate-1802",
  "Volta at Pavia, now in Paris: grant him a gratification.",
  "Le citoyen Sage fait connaître la situation malheureuse de Volta, professeur à Pavie, maintenant à Paris.",
  "Citizen Sage reports Volta's hard case at Paris."),
]

out = []
for iso, url, loc, toline, eid, ctx, fr, en in REC:
    push(out, NAP, "Consulate", iso, None, loc, "“" + en + " […]”",
         f"{toline}, {iso}", ARCH, url,
         "letter", ctx + TR, eid)
    out[-1]["originalText"] = fr
    out[-1]["originalLanguage"] = "French"

json.dump(out, open("data/nap_1801.json", "w"), ensure_ascii=False, indent=1)
print("1801:", len(out))
