#!/usr/bin/env python3
"""Tranche A: Mar-Jun 1796 French + own translations."""
import json, sys
sys.path.insert(0, "sources")
from common import push

NAP = {"author": "Napoleon Bonaparte", "handle": "@bonaparte", "accountType": "person"}
ARCH = "Correspondance de Napoléon Ier, Second Empire ed. (Paris, 1858), Vols. I–II — public domain (French)"
TR = " Translated for Chronicle from the public-domain French; original below."
U1 = "https://archive.org/details/correspondancede01napouoft"
U2 = "https://archive.org/details/correspondancede02napouoft"

# (iso, url, loc, toline, eid, ctx, fr, en)
REC = [
 ("1796-03-11", U1, "Nice", "To Letourneur (marriage)", "italy-1796",
  "Barras told: married to Citoyenne Tascher Beauharnais.",
  "J'avais chargé le citoyen Barras d'instruire le Directoire exécutif de mon mariage avec la citoyenne Tascher Beauharnais.",
  "I had Barras inform the Directory of my marriage to Citoyenne Tascher Beauharnais."),
 ("1796-03-27", U1, "Nice", "Proclamation at campaign opening", "italy-1796",
  "Nus, mal nourris: the most famous proclamation of the age.",
  "Soldats, vous êtes nus, mal nourris; le Gouvernement vous doit beaucoup, il ne peut rien vous donner.",
  "Soldiers, you are naked, ill-fed; the Government owes you much and can give you nothing."),
 ("1796-03-27", U1, "Nice", "To Chauvet (cavalry)", "italy-1796",
  "Cavalry movement states; regiments arriving daily.",
  "Vous trouverez ci-joint l'état du mouvement de la cavalerie; vous y verrez qu'il arrive des régiments.",
  "Enclosed the cavalry movement state; regiments arrive daily."),
 ("1796-03-21", U1, "Nice", "To Faypoult", "italy-1796",
  "Dined with Schérer and your wife; glad to oblige her.",
  "J'ai reçu votre lettre. J'ai diné aujourd'hui chez le général Schérer avec votre femme.",
  "Your letter received. I dined today with General Schérer and your wife."),
 ("1796-03-28", U1, "Nice", "To Carnot", "italy-1796",
  "Well received by the army; Schérer pure and enlightened.",
  "J'ai été très-bien reçu par l'armée, qui me montre une confiance qui m'oblige à une vive reconnaissance.",
  "Warmly received by the army, whose confidence obliges my liveliest gratitude."),
 ("1796-03-29", U1, "Nice", "To Berthier (mutiny)", "italy-1796",
  "209th refuses to march: disobedience and mutiny.",
  "Le 3e bataillon de la 209e demi-brigade s'est rendu coupable de désobéissance et d'esprit de mutinerie.",
  "The 209th's 3rd battalion stands guilty of disobedience and mutiny."),
 ("1796-03-29", U1, "Nice", "To Berthier (cavalry split)", "italy-1796",
  "Cavalry in two divisions: hussars, chasseurs assigned.",
  "La cavalerie sera partagée en deux divisions.",
  "The cavalry divides in two divisions."),
 ("1796-03-29", U1, "Nice", "To Parra (Antibes)", "italy-1796",
  "Antibes communes to furnish momentary supplies.",
  "Il est ordonné au général de brigade Parra de requérir sur-le-champ les corps administratifs de cette commune.",
  "General Parra will at once requisition Antibes' administrators."),
 ("1796-03-29", U1, "Nice", "Order of the day (review)", "italy-1796",
  "Reviewed 100th, 165th and Montfernie battalion.",
  "Le général en chef a passé la revue de la 100e demi-brigade et de la 165e.",
  "The General-in-Chief reviewed the 100th and 165th demi-brigades."),
 ("1796-03-31", U1, "Nice", "To Berthier (staff lists)", "italy-1796",
  "Tonight: staff, artillery and engineers lists for the 12th.",
  "Vous me remettrez ce soir l'état nominatif des officiers de l'état-major qui partent le 12.",
  "Tonight deliver the staff officers' roll marching on the 12th."),
 ("1796-03-31", U1, "Nice", "To Chabran (Albenga)", "italy-1796",
  "Chabran to Albenga post-haste, 11 Germinal.",
  "Il est ordonné à l'adjudant général Chabran de partir de Nice aujourd'hui pour se rendre le plus promptement à Albenga.",
  "Adjutant-General Chabran leaves Nice today for Albenga post-haste."),
 ("1796-04-03", U2, "Nice", "Order (organisation)", "italy-1796",
  "Hasten the new organisation work in every division.",
  "Le général en chef renouvelle l'ordre d'accélérer le travail relatif à la nouvelle organisation.",
  "The General-in-Chief renews orders to hasten the new organisation."),
 ("1796-04-04", U2, "Nice", "Order (Oneille)", "italy-1796",
  "400 sacks on Oneille valley, 200 on the district.",
  "Le général en chef ordonne une contribution de quatre cents sacs dans la vallée d'Oneille.",
  "A 400-sack contribution levied on Oneille valley."),
 ("1796-04-05", U2, "Nice", "To Berthier (Moulin)", "italy-1796",
  "Émigré Moulin to military commission at Nice.",
  "Vous voudrez bien faire réunir une commission militaire à Nice pour y juger l'émigré Moulin, pris à Ormea.",
  "Convene a Nice military commission for émigré Moulin, taken at Ormea."),
 ("1796-04-06", U2, "Albenga", "To Berthier (convoys)", "italy-1796",
  "Mule brigades Laigueglia–Pietra for forage and hospitals.",
  "Vous donnerez les ordres pour qu'il soit levé, pour les charrois, fourrages et hôpitaux, une brigade de Laigueglia à Pietra.",
  "Raise a Laigueglia–Pietra brigade for carts, forage, hospitals."),
 ("1796-04-06", U2, "Albenga", "Order (review)", "italy-1796",
  "39th and 69th reviewed with published satisfaction.",
  "Le général en chef a passé la revue des 39e et 69e demi-brigades, avec satisfaction publiée par la voie de l'ordre.",
  "Reviewed the 39th and 69th with published satisfaction."),
 ("1796-04-07", U2, "Albenga", "To Berthier (mules)", "italy-1796",
  "Two hundred mules at Pieve, Ormea, Garessio for food.",
  "Vous donnerez l'ordre pour que l'on lève à Pieve, Ormea et Garessio, une division de deux cents mulets, pour les vivres.",
  "Levy two hundred mules at Pieve, Ormea and Garessio for food."),
 ("1796-04-08", U2, "Albenga", "To Colli (émigrés)", "italy-1796",
  "An émigré is a parricidal son; his presence dishonours your army.",
  "Monsieur, un émigré est un fils parricide qu'aucun caractère ne peut rendre sacré; ceux qui sont dans votre armée la déshonorent.",
  "Sir, an émigré is a parricidal son no rank can sanctify; yours dishonour your army."),
 ("1796-04-10", U2, "Albenga", "To Genoa (patriots)", "italy-1796",
  "Genoa molests patriots while sheltering émigrés.",
  "J'apprends que le Gouvernement de Gênes moleste les patriotes et inquiète les amis de la France.",
  "I learn Genoa molests patriots and troubles France's friends."),
 ("1796-04-11", U2, "Albenga", "To Augereau (ready)", "italy-1796",
  "Troops ready to march at first signal, with food issued.",
  "Je vous donne l'ordre de tenir les troupes prêtes à marcher au premier signal, avec les vivres distribués.",
  "Hold your troops ready to march at first signal, food issued."),
 ("1796-04-11", U2, "Albenga", "To Augereau (Mallare)", "italy-1796",
  "Two demi-brigades and four squadrons to Mallare by shortest road.",
  "Le général Augereau partira avec ses deux demi-brigades et quatre escadrons pour Mallare par le plus court chemin.",
  "Augereau marches two demi-brigades and four squadrons to Mallare."),
 ("1796-04-11", U2, "Finale", "Artillery order", "italy-1796",
  "8-pounder, two 4s, howitzer, two 3s: march with all munitions.",
  "Il est ordonné à l'officier d'artillerie à Finale de partir avec la pièce de 8, deux pièces de 4, un obusier et toutes ses munitions.",
  "Finale's artillery marches with 8-pounder, 4s, howitzer and all munitions."),
 ("1796-05-02", U2, "Italy", "To Augereau (Frugarolo)", "italy-1796",
  "Rusca's brigade into Frugarolo, well guarded.",
  "Le général Augereau placera la brigade du général Rusca dans la ville de Frugarolo, bien gardée.",
  "Augereau posts Rusca's brigade in Frugarolo, well guarded."),
 ("1796-05-02", U2, "Italy", "To Beaumont (cavalry)", "italy-1796",
  "Cavalry bivouacked left beyond Friugarolo toward Laharpe.",
  "Le général Beaumont bivouaquera la cavalerie, la gauche en arrière du village de Friugarolo.",
  "Beaumont bivouacs the cavalry left beyond Friugarolo village."),
 ("1796-05-03", U2, "Bosco", "To Laharpe (Tortona)", "italy-1796",
  "Cross the Scrivia at once with all, enter Tortona.",
  "Il est ordonné au général Laharpe de passer sur-le-champ la Scrivia avec toute sa division, et d'entrer à Tortone.",
  "Laharpe crosses the Scrivia at once with all and enters Tortona."),
 ("1796-05-03", U2, "Bosco", "To Laharpe (Novi bread)", "italy-1796",
  "Fifty chasseurs to Novi: fifteen thousand bread rations today.",
  "Tu voudras bien faire partir cinquante chasseurs pour Novi, de te faire dans le jour quinze mille rations de pain.",
  "Send fifty chasseurs to Novi for fifteen thousand bread rations today."),
 ("1796-05-03", U2, "Bosco", "To Pelletier (Serravalle)", "italy-1796",
  "Half his troops to Serravalle castle at once.",
  "Il est ordonné au général Pelletier de partir avec la moitié des troupes pour Serravalle.",
  "Pelletier marches half his troops to Serravalle at once."),
 ("1796-05-03", U2, "Sale", "To Masséna (boats)", "italy-1796",
  "Guards on Bassignana boats, right bank held, none pass at Dozena.",
  "Le général Masséna enverra une garde pour s'emparer des barques de Bassignana, rive droite tenue.",
  "Masséna seizes Bassignana boats, holds the right bank."),
 ("1796-05-03", U2, "Bosco", "To Solar (Alexandria)", "italy-1796",
  "Thanks for obliging intelligence, Monsieur.",
  "J'ai reçu, Monsieur, la lettre que vous m'avez écrite. Je vous suis très-obligé des renseignements.",
  "Your letter received, Sir, with thanks for the obliging intelligence."),
 ("1796-05-04", U2, "Tortona", "To Tortona municipality", "italy-1796",
  "Warned: inhabitants pillaged; Beaumont's horsemen guilty.",
  "Le général en chef est prévenu que beaucoup d'habitants ont été pillés par des cavaliers.",
  "The General-in-Chief is warned inhabitants were pillaged by horsemen."),
 ("1796-05-04", U2, "Tortona", "To Masséna (Tanaro)", "italy-1796",
  "Every Tanaro and Bassignana boat down to Sale without delay.",
  "Il est ordonné au général Masséna de faire descendre sans délai, vis-à-vis Sale, tous les bateaux du Tanaro.",
  "Masséna floats every Tanaro boat down to Sale without delay."),
 ("1796-05-04", U2, "Tortona", "To Augereau (Po)", "italy-1796",
  "No Po communication; stop and seize every passing boat.",
  "Il est ordonné au général Augereau de ne souffrir aucune communication entre les deux rives du Pô, et d'arrêter tous les bateaux.",
  "Augereau suffers no Po communication; every boat stopped and seized."),
 ("1796-06-02", U2, "Peschiera", "To Sugny (forts)", "italy-1796",
  "Every engineering means into Peschiera fortifications, instantly.",
  "Le commandant du génie a ordre d'employer tous les moyens de l'art pour accroître les fortifications de Peschiera.",
  "Engineers throw every means into Peschiera's fortifications, instantly."),
 ("1796-06-02", U2, "Peschiera", "To Boyer (Castiglione)", "italy-1796",
  "Boyer to Castiglione-Mantovano to warn Augereau.",
  "L'adjudant général Boyer partira pour Castiglione-Mantovano, où il trouvera le général Augereau.",
  "Adjutant Boyer rides to Castiglione-Mantovano to warn Augereau."),
 ("1796-06-02", U2, "Peschiera", "To Lambert (couriers)", "italy-1796",
  "Paris correspondence via Lyon-Chambéry-Turin direct.",
  "L'intention du général en chef étant d'établir la correspondance avec Paris par Lyon, Chambéry et Turin directement.",
  "Paris correspondence runs direct via Lyon, Chambéry, Turin."),
 ("1796-06-03", U2, "Verona", "To the Directory", "italy-1796",
  "Great and beautiful city held; good garrison masters it.",
  "J'arrive dans cette ville, qui est très-grande et très-belle. J'y laisse une bonne garnison.",
  "I reach this great beautiful city, leaving a good garrison."),
 ("1796-06-03", U2, "Verona", "To Sérurier", "italy-1796",
  "Auxiliary officer to Roverbella headquarters at once.",
  "Il est ordonné au général Serurier d'envoyer sur-le-champ à Roverbella un des officiers auxiliaires.",
  "Sérurier sends an auxiliary officer to Roverbella headquarters at once."),
 ("1796-06-03", U2, "Verona", "To Kilmaine", "italy-1796",
  "All the 10th chasseurs to Roverbella headquarters.",
  "Il est ordonné au général Kilmaine de faire partir tout le 10e chasseurs pour le quartier général à Roverbella.",
  "Kilmaine sends all the 10th chasseurs to Roverbella headquarters."),
 ("1796-06-03", U2, "Verona", "To Andréossy (dawn)", "italy-1796",
  "Andréossy at Castiglione by 5 a.m. to catch the enemy.",
  "Il est ordonné au citoyen Andréossy d'être rendu demain, à cinq heures du matin, à Castiglione-Mantovano.",
  "Andréossy at Castiglione-Mantovano by 5 a.m. tomorrow."),
]

out = []
for iso, url, loc, toline, eid, ctx, fr, en in REC:
    push(out, NAP, "Army of Italy", iso, None, loc, "“" + en + " […]”",
         f"{toline}, {iso}", ARCH, url,
         "letter", ctx + TR, eid)
    out[-1]["originalText"] = fr
    out[-1]["originalLanguage"] = "French"

json.dump(out, open("data/nap_trancheA.json", "w"), ensure_ascii=False, indent=1)
print("trancheA:", len(out))
